### PR TITLE
Upgrade to v0.14.0

### PR DESCRIPTION
**Pull request by tituspijean**
## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by thebaer** [comment]
Just a heads up that the original v0.14 release [accidentally included](https://writing.exchange/@andi1984@toot.cafe/111127412665410005) a `static/local/custom.css` file, which will cause every instance using that build to have a dark-themed blog. The entire `static/local/` directory should've been excluded from the build, and that's fixed now. But you all might want to grab the latest release before sending this out!

**Comment by tituspijean** [comment]
Hello @thebaer, thanks for the heads up! I am a bit confused though.
I see that [the fix](https://github.com/writefreely/writefreely/commit/62f9b2948ecaf6e8b4362570bf0e55111a24a183) is not published in a release yet, but none of the release files in https://github.com/writefreely/writefreely/releases/tag/v0.14.0 contain a `static/local` directory. (and they were published half an hour before your fix commit).

I have also just installed Writefreely from this testing branch, and it indeed does not have css issues as @andi1984 had.

**Comment by thebaer** [comment]
Right, I fixed the release itself before committing the fix for future builds. But if you have the release that doesn't include the directory, then it's all good!

**Comment by tituspijean** [comment]
!testme

**Pull request merged**
